# Generated by Django 5.1.6 on 2026-02-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='warehouse_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='warehouse_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inboundorder',
            name='status',
            field=models.CharField(default='草稿', max_length=30),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(default='草稿', max_length=30),
        ),
        migrations.CreateModel(
            name='InboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.inboundorder')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.outboundorder')),
            ],
        ),
    ]
