# Generated by Django 5.1.6 on 2026-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inboundorder_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorder',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inboundorder',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inboundorderitem',
            name='location_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inboundorderitem',
            name='putaway_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboundorderitem',
            name='received_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inboundorderitem',
            name='status',
            field=models.CharField(default='草稿', max_length=30),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
