# Generated by Django 5.1.6 on 2026-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inboundorder_reject_reason_inboundorder_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStocktaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50)),
                ('product_sku', models.CharField(max_length=50)),
                ('location_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_before', models.IntegerField(default=0)),
                ('quantity_after', models.IntegerField(default=0)),
                ('diff_qty', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('from_warehouse', models.CharField(max_length=50)),
                ('to_warehouse', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
