# Generated by Django 4.2.16 on 2026-03-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventorystocktaking_inventorytransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundorderitem',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
