# Generated by Django 4.2.16 on 2026-04-17 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_inboundorderitem_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundorderitem',
            name='putaway_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inboundorderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inboundorderitem',
            name='received_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='locked_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='outboundorderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='inboundorderitem',
            index=models.Index(fields=['product_sku'], name='api_inbound_product_c28478_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product_sku', 'warehouse_code'], name='api_invento_product_abef81_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product_sku', 'warehouse_code', 'location_code'], name='api_invento_product_bafd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorderitem',
            index=models.Index(fields=['product_sku'], name='api_outboun_product_f04c47_idx'),
        ),
    ]
